[workspace]
members = [
    "migrate",
    "types",
]

[workspace.dependencies]
async-nats = "0.27"
aurora-refiner-types = { git = "https://github.com/aurora-is-near/borealis-engine-lib.git", tag = "v0.17.1" }
borealis-rs = { git = "ssh://git@github.com/aurora-is-near/borealis.rs.git", rev = "2065be6" }
borealis-types = { git = "ssh://git@github.com/aurora-is-near/borealis.rs.git", rev = "2065be6" }
futures-util = "0.3"
prost = "0.11"
zstd = "0.12"
zstd-sys = "2"
