[workspace]
resolver = "2"
members = [
    "migrate",
    "types",
]

[workspace.dependencies]
async-nats = "0.31"
aurora-refiner-types = { git = "https://github.com/aurora-is-near/borealis-engine-lib.git", rev = "bdd62f0b8dab9eeef23fee827c9d1ab14be8d2a9" }
borealis-rs = { git = "ssh://git@github.com/aurora-is-near/borealis.rs.git", rev = "8a8b9bcf6f020a5940b1566e17b7130e30e2c669" }
bytes = "1"
futures-util = "0.3"
near-crypto = { git = "https://github.com/near/nearcore", tag = "1.35.0" }
near-primitives = { git = "https://github.com/near/nearcore", tag = "1.35.0" }
near-vm-errors = { git = "https://github.com/near/nearcore", tag = "1.35.0" }
prost = "0.11"
zstd = "0.12"
zstd-sys = "2"
