[workspace]
members = [
    "migrate",
    "types",
]

[workspace.dependencies]
async-nats = "0.27"
aurora-refiner-types = { git = "https://github.com/aurora-is-near/borealis-engine-lib.git", tag = "v0.21.0" }
borealis-rs = { git = "ssh://git@github.com/aurora-is-near/borealis.rs.git", tag = "v0.13.3" }
bytes = "2"
futures-util = "0.3"
near-crypto = { git = "https://github.com/near/nearcore", tag = "1.34.0" }
near-primitives = { git = "https://github.com/near/nearcore", tag = "1.34.0" }
near-vm-errors = { git = "https://github.com/near/nearcore", tag = "1.34.0" }
prost = "0.11"
zstd = "0.12"
zstd-sys = "2"
