[package]
name = "borealis-proto"
version = "0.1.0"
edition = "2021"

[dependencies]
borealis-types = { git = "ssh://git@github.com/aurora-is-near/borealis.rs.git", tag = "borealis-rs-v0.2.0" }
near-primitives = { git = "https://github.com/near/nearcore", tag = "1.29.0-rc.1" }
near-crypto = { git = "https://github.com/near/nearcore", tag = "1.29.0-rc.1" }
near-vm-errors = { git = "https://github.com/near/nearcore", tag = "1.29.0-rc.1" }
bytes = "1"
prost = "0.11"
clap = { version = "4", features = ["derive"] }
nats = "0.23"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
chrono = "0.4"
bs58 = "0.4"
time = { version = "0.3", features = ["macros"] }
async-nats = { version = "0.26" }

[dev-dependencies]
sha2 = "0.10"
ed25519-dalek = "1"

[build-dependencies]
prost-build = { version = "0.11" }
