[workspace]
resolver = "2"
members = [
    "migrate",
    "types",
]

[workspace.dependencies]
async-nats = "0.31"
aurora-refiner-types = { git = "https://github.com/aurora-is-near/borealis-engine-lib.git", tag = "silo-0.23.3" }
borealis-rs = { git = "ssh://git@github.com/aurora-is-near/borealis.rs.git", tag = "silo-0.16.3" }
bytes = "1"
futures-util = "0.3"
near-crypto = { git = "https://github.com/near/nearcore", tag = "1.35.0" }
near-primitives = { git = "https://github.com/near/nearcore", tag = "1.35.0" }
near-vm-errors = { git = "https://github.com/near/nearcore", tag = "1.35.0" }
prost = "0.11"
zstd = "0.12"
zstd-sys = "2"
