[package]
name = "borealis-proto-types"
version = "0.3.0"
edition = "2021"

[dependencies]
async-nats = { version = "0.27", optional = true }
aurora-refiner-types = { workspace = true }
aurora-near-crypto = { git = "https://github.com/near/nearcore", tag = "1.26.1", package = "near-crypto" }
aurora-near-primitives = { git = "https://github.com/near/nearcore", tag = "1.26.1", package = "near-primitives" }
aurora-near-vm-errors = { git = "https://github.com/near/nearcore", tag = "1.26.1", package = "near-vm-errors", features = ["protocol_feature_alt_bn128"] }
borealis-types = { workspace = true }
borealis-rs = { workspace = true }
bs58 = "0.4"
bytes = "1"
chrono = "0.4"
log = "0.4"
near-crypto = { git = "https://github.com/near/nearcore", tag = "1.29.0-rc.1" }
near-primitives = { git = "https://github.com/near/nearcore", tag = "1.29.0-rc.1" }
near-vm-errors = { git = "https://github.com/near/nearcore", tag = "1.29.0-rc.1" }
prost = { workspace = true }
thiserror = "1"
itertools = "0.10"
ed25519-dalek = "1"
zstd = { workspace = true }
zstd-sys = { workspace = true }

[dev-dependencies]
sha2 = "0.10"
test-case = "3"

[build-dependencies]
prost-build = { version = "0.11" }
