[package]
name = "borealis-proto-types"
version = "0.1.0"
edition = "2021"

[dependencies]
borealis-types = { git = "ssh://git@github.com/aurora-is-near/borealis.rs.git", tag = "borealis-rs-v0.2.0" }
bs58 = "0.4"
bytes = "1"
chrono = "0.4"
log = "0.4"
near-crypto = { git = "https://github.com/near/nearcore", tag = "1.29.0-rc.1" }
near-primitives = { git = "https://github.com/near/nearcore", tag = "1.29.0-rc.1" }
near-vm-errors = { git = "https://github.com/near/nearcore", tag = "1.29.0-rc.1" }
prost = "0.11"
thiserror = "1"
itertools = "0.10"
ed25519-dalek = "1"
zstd = "0.10.0+zstd.1.5.2"
zstd-sys = "1.6.3+zstd.1.5.2"

[dev-dependencies]
sha2 = "0.10"

[build-dependencies]
prost-build = { version = "0.11" }
