[package]
name = "borealis-proto-migrate"
version = "0.1.0"
edition = "2021"

[dependencies]
borealis-proto-types = { path = "../types" }
anyhow = "1"
async-nats = { version = "0.26" }
borealis-types = { git = "ssh://git@github.com/aurora-is-near/borealis.rs.git", tag = "borealis-rs-v0.2.0" }
chrono = "0.4"
clap = { version = "4", features = ["derive"] }
env_logger = "0.10"
futures-util = "0.3"
futures = "0.3"
log = "0.4"
prost = "0.11"
thiserror = "1"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
zstd = "0.12"
zstd-sys = "2"
