// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.6.0
// source: blocksapi/services.proto

package blocksapi

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// BlocksProviderClient is the client API for BlocksProvider service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type BlocksProviderClient interface {
	// Returns information about available block streams
	ListBlockStreams(ctx context.Context, in *ListBlockStreamsRequest, opts ...grpc.CallOption) (*ListBlockStreamsResponse, error)
	// Reads individual message
	ReadMessage(ctx context.Context, in *ReadMessageRequest, opts ...grpc.CallOption) (*ReadMessageResponse, error)
	// Streams blocks continiously
	StreamBlocks(ctx context.Context, in *BlockStreamRequest, opts ...grpc.CallOption) (BlocksProvider_StreamBlocksClient, error)
}

type blocksProviderClient struct {
	cc grpc.ClientConnInterface
}

func NewBlocksProviderClient(cc grpc.ClientConnInterface) BlocksProviderClient {
	return &blocksProviderClient{cc}
}

func (c *blocksProviderClient) ListBlockStreams(ctx context.Context, in *ListBlockStreamsRequest, opts ...grpc.CallOption) (*ListBlockStreamsResponse, error) {
	out := new(ListBlockStreamsResponse)
	err := c.cc.Invoke(ctx, "/BlocksProvider/ListBlockStreams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blocksProviderClient) ReadMessage(ctx context.Context, in *ReadMessageRequest, opts ...grpc.CallOption) (*ReadMessageResponse, error) {
	out := new(ReadMessageResponse)
	err := c.cc.Invoke(ctx, "/BlocksProvider/ReadMessage", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blocksProviderClient) StreamBlocks(ctx context.Context, in *BlockStreamRequest, opts ...grpc.CallOption) (BlocksProvider_StreamBlocksClient, error) {
	stream, err := c.cc.NewStream(ctx, &BlocksProvider_ServiceDesc.Streams[0], "/BlocksProvider/StreamBlocks", opts...)
	if err != nil {
		return nil, err
	}
	x := &blocksProviderStreamBlocksClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type BlocksProvider_StreamBlocksClient interface {
	Recv() (*BlockStreamResponse, error)
	grpc.ClientStream
}

type blocksProviderStreamBlocksClient struct {
	grpc.ClientStream
}

func (x *blocksProviderStreamBlocksClient) Recv() (*BlockStreamResponse, error) {
	m := new(BlockStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// BlocksProviderServer is the server API for BlocksProvider service.
// All implementations must embed UnimplementedBlocksProviderServer
// for forward compatibility
type BlocksProviderServer interface {
	// Returns information about available block streams
	ListBlockStreams(context.Context, *ListBlockStreamsRequest) (*ListBlockStreamsResponse, error)
	// Reads individual message
	ReadMessage(context.Context, *ReadMessageRequest) (*ReadMessageResponse, error)
	// Streams blocks continiously
	StreamBlocks(*BlockStreamRequest, BlocksProvider_StreamBlocksServer) error
	mustEmbedUnimplementedBlocksProviderServer()
}

// UnimplementedBlocksProviderServer must be embedded to have forward compatible implementations.
type UnimplementedBlocksProviderServer struct {
}

func (UnimplementedBlocksProviderServer) ListBlockStreams(context.Context, *ListBlockStreamsRequest) (*ListBlockStreamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListBlockStreams not implemented")
}
func (UnimplementedBlocksProviderServer) ReadMessage(context.Context, *ReadMessageRequest) (*ReadMessageResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadMessage not implemented")
}
func (UnimplementedBlocksProviderServer) StreamBlocks(*BlockStreamRequest, BlocksProvider_StreamBlocksServer) error {
	return status.Errorf(codes.Unimplemented, "method StreamBlocks not implemented")
}
func (UnimplementedBlocksProviderServer) mustEmbedUnimplementedBlocksProviderServer() {}

// UnsafeBlocksProviderServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlocksProviderServer will
// result in compilation errors.
type UnsafeBlocksProviderServer interface {
	mustEmbedUnimplementedBlocksProviderServer()
}

func RegisterBlocksProviderServer(s grpc.ServiceRegistrar, srv BlocksProviderServer) {
	s.RegisterService(&BlocksProvider_ServiceDesc, srv)
}

func _BlocksProvider_ListBlockStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListBlockStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlocksProviderServer).ListBlockStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BlocksProvider/ListBlockStreams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlocksProviderServer).ListBlockStreams(ctx, req.(*ListBlockStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlocksProvider_ReadMessage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReadMessageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlocksProviderServer).ReadMessage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/BlocksProvider/ReadMessage",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlocksProviderServer).ReadMessage(ctx, req.(*ReadMessageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlocksProvider_StreamBlocks_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BlockStreamRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(BlocksProviderServer).StreamBlocks(m, &blocksProviderStreamBlocksServer{stream})
}

type BlocksProvider_StreamBlocksServer interface {
	Send(*BlockStreamResponse) error
	grpc.ServerStream
}

type blocksProviderStreamBlocksServer struct {
	grpc.ServerStream
}

func (x *blocksProviderStreamBlocksServer) Send(m *BlockStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

// BlocksProvider_ServiceDesc is the grpc.ServiceDesc for BlocksProvider service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlocksProvider_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "BlocksProvider",
	HandlerType: (*BlocksProviderServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListBlockStreams",
			Handler:    _BlocksProvider_ListBlockStreams_Handler,
		},
		{
			MethodName: "ReadMessage",
			Handler:    _BlocksProvider_ReadMessage_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamBlocks",
			Handler:       _BlocksProvider_StreamBlocks_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "blocksapi/services.proto",
}
