// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v3.21.12
// source: blocksapi/stream_list.proto

package blocksapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListBlockStreamsErrorClass int32

const (
	// Default error class
	ListBlockStreamsErrorClass_LIST_ERROR_UNKNOWN ListBlockStreamsErrorClass = 0
)

// Enum value maps for ListBlockStreamsErrorClass.
var (
	ListBlockStreamsErrorClass_name = map[int32]string{
		0: "LIST_ERROR_UNKNOWN",
	}
	ListBlockStreamsErrorClass_value = map[string]int32{
		"LIST_ERROR_UNKNOWN": 0,
	}
)

func (x ListBlockStreamsErrorClass) Enum() *ListBlockStreamsErrorClass {
	p := new(ListBlockStreamsErrorClass)
	*p = x
	return p
}

func (x ListBlockStreamsErrorClass) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListBlockStreamsErrorClass) Descriptor() protoreflect.EnumDescriptor {
	return file_blocksapi_stream_list_proto_enumTypes[0].Descriptor()
}

func (ListBlockStreamsErrorClass) Type() protoreflect.EnumType {
	return &file_blocksapi_stream_list_proto_enumTypes[0]
}

func (x ListBlockStreamsErrorClass) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListBlockStreamsErrorClass.Descriptor instead.
func (ListBlockStreamsErrorClass) EnumDescriptor() ([]byte, []int) {
	return file_blocksapi_stream_list_proto_rawDescGZIP(), []int{0}
}

type ListBlockStreamsRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	StreamFilter []string `protobuf:"bytes,1,rep,name=stream_filter,json=streamFilter,proto3" json:"stream_filter,omitempty"`
}

func (x *ListBlockStreamsRequest) Reset() {
	*x = ListBlockStreamsRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blocksapi_stream_list_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBlockStreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockStreamsRequest) ProtoMessage() {}

func (x *ListBlockStreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_blocksapi_stream_list_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockStreamsRequest.ProtoReflect.Descriptor instead.
func (*ListBlockStreamsRequest) Descriptor() ([]byte, []int) {
	return file_blocksapi_stream_list_proto_rawDescGZIP(), []int{0}
}

func (x *ListBlockStreamsRequest) GetStreamFilter() []string {
	if x != nil {
		return x.StreamFilter
	}
	return nil
}

type ListBlockStreamsError struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ErrorClass  ListBlockStreamsErrorClass `protobuf:"varint,1,opt,name=error_class,json=errorClass,proto3,enum=ListBlockStreamsErrorClass" json:"error_class,omitempty"`
	Description string                     `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *ListBlockStreamsError) Reset() {
	*x = ListBlockStreamsError{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blocksapi_stream_list_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBlockStreamsError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockStreamsError) ProtoMessage() {}

func (x *ListBlockStreamsError) ProtoReflect() protoreflect.Message {
	mi := &file_blocksapi_stream_list_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockStreamsError.ProtoReflect.Descriptor instead.
func (*ListBlockStreamsError) Descriptor() ([]byte, []int) {
	return file_blocksapi_stream_list_proto_rawDescGZIP(), []int{1}
}

func (x *ListBlockStreamsError) GetErrorClass() ListBlockStreamsErrorClass {
	if x != nil {
		return x.ErrorClass
	}
	return ListBlockStreamsErrorClass_LIST_ERROR_UNKNOWN
}

func (x *ListBlockStreamsError) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type ListBlockStreamsResult struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Response map[string]*BlockStreamInfo `protobuf:"bytes,1,rep,name=response,proto3" json:"response,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
}

func (x *ListBlockStreamsResult) Reset() {
	*x = ListBlockStreamsResult{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blocksapi_stream_list_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBlockStreamsResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockStreamsResult) ProtoMessage() {}

func (x *ListBlockStreamsResult) ProtoReflect() protoreflect.Message {
	mi := &file_blocksapi_stream_list_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockStreamsResult.ProtoReflect.Descriptor instead.
func (*ListBlockStreamsResult) Descriptor() ([]byte, []int) {
	return file_blocksapi_stream_list_proto_rawDescGZIP(), []int{2}
}

func (x *ListBlockStreamsResult) GetResponse() map[string]*BlockStreamInfo {
	if x != nil {
		return x.Response
	}
	return nil
}

type ListBlockStreamsResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Response:
	//
	//	*ListBlockStreamsResponse_Result
	//	*ListBlockStreamsResponse_Error
	Response isListBlockStreamsResponse_Response `protobuf_oneof:"response"`
}

func (x *ListBlockStreamsResponse) Reset() {
	*x = ListBlockStreamsResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_blocksapi_stream_list_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListBlockStreamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListBlockStreamsResponse) ProtoMessage() {}

func (x *ListBlockStreamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_blocksapi_stream_list_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListBlockStreamsResponse.ProtoReflect.Descriptor instead.
func (*ListBlockStreamsResponse) Descriptor() ([]byte, []int) {
	return file_blocksapi_stream_list_proto_rawDescGZIP(), []int{3}
}

func (m *ListBlockStreamsResponse) GetResponse() isListBlockStreamsResponse_Response {
	if m != nil {
		return m.Response
	}
	return nil
}

func (x *ListBlockStreamsResponse) GetResult() *ListBlockStreamsResult {
	if x, ok := x.GetResponse().(*ListBlockStreamsResponse_Result); ok {
		return x.Result
	}
	return nil
}

func (x *ListBlockStreamsResponse) GetError() *ListBlockStreamsError {
	if x, ok := x.GetResponse().(*ListBlockStreamsResponse_Error); ok {
		return x.Error
	}
	return nil
}

type isListBlockStreamsResponse_Response interface {
	isListBlockStreamsResponse_Response()
}

type ListBlockStreamsResponse_Result struct {
	Result *ListBlockStreamsResult `protobuf:"bytes,1,opt,name=result,proto3,oneof"`
}

type ListBlockStreamsResponse_Error struct {
	Error *ListBlockStreamsError `protobuf:"bytes,2,opt,name=error,proto3,oneof"`
}

func (*ListBlockStreamsResponse_Result) isListBlockStreamsResponse_Response() {}

func (*ListBlockStreamsResponse_Error) isListBlockStreamsResponse_Response() {}

var File_blocksapi_stream_list_proto protoreflect.FileDescriptor

var file_blocksapi_stream_list_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x62,
	0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x61, 0x70, 0x69, 0x2f, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f,
	0x69, 0x6e, 0x66, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3e, 0x0a, 0x17, 0x4c, 0x69,
	0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x73, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x5f,
	0x66, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x73, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x46, 0x69, 0x6c, 0x74, 0x65, 0x72, 0x22, 0x77, 0x0a, 0x15, 0x4c, 0x69,
	0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x45, 0x72,
	0x72, 0x6f, 0x72, 0x12, 0x3c, 0x0a, 0x0b, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x5f, 0x63, 0x6c, 0x61,
	0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42,
	0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x45, 0x72, 0x72, 0x6f, 0x72,
	0x43, 0x6c, 0x61, 0x73, 0x73, 0x52, 0x0a, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6c, 0x61, 0x73,
	0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x22, 0xaa, 0x01, 0x0a, 0x16, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63,
	0x6b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x41,
	0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b,
	0x32, 0x25, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x72, 0x65,
	0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x2e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x1a, 0x4d, 0x0a, 0x0d, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x45, 0x6e, 0x74,
	0x72, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6b, 0x65, 0x79, 0x12, 0x26, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01,
	0x22, 0x89, 0x01, 0x0a, 0x18, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x31, 0x0a,
	0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73,
	0x52, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74,
	0x12, 0x2e, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x72, 0x65, 0x61,
	0x6d, 0x73, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x48, 0x00, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72,
	0x42, 0x0a, 0x0a, 0x08, 0x72, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x2a, 0x34, 0x0a, 0x1a,
	0x4c, 0x69, 0x73, 0x74, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x73,
	0x45, 0x72, 0x72, 0x6f, 0x72, 0x43, 0x6c, 0x61, 0x73, 0x73, 0x12, 0x16, 0x0a, 0x12, 0x4c, 0x49,
	0x53, 0x54, 0x5f, 0x45, 0x52, 0x52, 0x4f, 0x52, 0x5f, 0x55, 0x4e, 0x4b, 0x4e, 0x4f, 0x57, 0x4e,
	0x10, 0x00, 0x42, 0x46, 0x5a, 0x44, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d,
	0x2f, 0x61, 0x75, 0x72, 0x6f, 0x72, 0x61, 0x2d, 0x69, 0x73, 0x2d, 0x6e, 0x65, 0x61, 0x72, 0x2f,
	0x62, 0x6f, 0x72, 0x65, 0x61, 0x6c, 0x69, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x74, 0x79,
	0x70, 0x65, 0x73, 0x2f, 0x67, 0x6f, 0x2f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x61, 0x70, 0x69,
	0x3b, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x73, 0x61, 0x70, 0x69, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_blocksapi_stream_list_proto_rawDescOnce sync.Once
	file_blocksapi_stream_list_proto_rawDescData = file_blocksapi_stream_list_proto_rawDesc
)

func file_blocksapi_stream_list_proto_rawDescGZIP() []byte {
	file_blocksapi_stream_list_proto_rawDescOnce.Do(func() {
		file_blocksapi_stream_list_proto_rawDescData = protoimpl.X.CompressGZIP(file_blocksapi_stream_list_proto_rawDescData)
	})
	return file_blocksapi_stream_list_proto_rawDescData
}

var file_blocksapi_stream_list_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_blocksapi_stream_list_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_blocksapi_stream_list_proto_goTypes = []interface{}{
	(ListBlockStreamsErrorClass)(0),  // 0: ListBlockStreamsErrorClass
	(*ListBlockStreamsRequest)(nil),  // 1: ListBlockStreamsRequest
	(*ListBlockStreamsError)(nil),    // 2: ListBlockStreamsError
	(*ListBlockStreamsResult)(nil),   // 3: ListBlockStreamsResult
	(*ListBlockStreamsResponse)(nil), // 4: ListBlockStreamsResponse
	nil,                              // 5: ListBlockStreamsResult.ResponseEntry
	(*BlockStreamInfo)(nil),          // 6: BlockStreamInfo
}
var file_blocksapi_stream_list_proto_depIdxs = []int32{
	0, // 0: ListBlockStreamsError.error_class:type_name -> ListBlockStreamsErrorClass
	5, // 1: ListBlockStreamsResult.response:type_name -> ListBlockStreamsResult.ResponseEntry
	3, // 2: ListBlockStreamsResponse.result:type_name -> ListBlockStreamsResult
	2, // 3: ListBlockStreamsResponse.error:type_name -> ListBlockStreamsError
	6, // 4: ListBlockStreamsResult.ResponseEntry.value:type_name -> BlockStreamInfo
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_blocksapi_stream_list_proto_init() }
func file_blocksapi_stream_list_proto_init() {
	if File_blocksapi_stream_list_proto != nil {
		return
	}
	file_blocksapi_stream_info_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_blocksapi_stream_list_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBlockStreamsRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blocksapi_stream_list_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBlockStreamsError); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blocksapi_stream_list_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBlockStreamsResult); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_blocksapi_stream_list_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListBlockStreamsResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_blocksapi_stream_list_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*ListBlockStreamsResponse_Result)(nil),
		(*ListBlockStreamsResponse_Error)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_blocksapi_stream_list_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_blocksapi_stream_list_proto_goTypes,
		DependencyIndexes: file_blocksapi_stream_list_proto_depIdxs,
		EnumInfos:         file_blocksapi_stream_list_proto_enumTypes,
		MessageInfos:      file_blocksapi_stream_list_proto_msgTypes,
	}.Build()
	File_blocksapi_stream_list_proto = out.File
	file_blocksapi_stream_list_proto_rawDesc = nil
	file_blocksapi_stream_list_proto_goTypes = nil
	file_blocksapi_stream_list_proto_depIdxs = nil
}
