// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.0
// 	protoc        v3.21.12
// source: payloads/near_block/transaction/receipt.proto

package transaction

import (
	common "github.com/aurora-is-near/borealis-prototypes/go/common"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReceiptView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PredecessorId string           `protobuf:"bytes,1,opt,name=predecessor_id,json=predecessorId,proto3" json:"predecessor_id,omitempty"`
	ReceiverId    string           `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	H256ReceiptId []byte           `protobuf:"bytes,3,opt,name=h256_receipt_id,json=h256ReceiptId,proto3" json:"h256_receipt_id,omitempty"`
	Receipt       *ReceiptEnumView `protobuf:"bytes,4,opt,name=receipt,proto3" json:"receipt,omitempty"`
}

func (x *ReceiptView) Reset() {
	*x = ReceiptView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiptView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptView) ProtoMessage() {}

func (x *ReceiptView) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptView.ProtoReflect.Descriptor instead.
func (*ReceiptView) Descriptor() ([]byte, []int) {
	return file_payloads_near_block_transaction_receipt_proto_rawDescGZIP(), []int{0}
}

func (x *ReceiptView) GetPredecessorId() string {
	if x != nil {
		return x.PredecessorId
	}
	return ""
}

func (x *ReceiptView) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *ReceiptView) GetH256ReceiptId() []byte {
	if x != nil {
		return x.H256ReceiptId
	}
	return nil
}

func (x *ReceiptView) GetReceipt() *ReceiptEnumView {
	if x != nil {
		return x.Receipt
	}
	return nil
}

type ReceiptEnumView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Variant:
	//
	//	*ReceiptEnumView_Action_
	//	*ReceiptEnumView_Data_
	Variant isReceiptEnumView_Variant `protobuf_oneof:"variant"`
}

func (x *ReceiptEnumView) Reset() {
	*x = ReceiptEnumView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiptEnumView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptEnumView) ProtoMessage() {}

func (x *ReceiptEnumView) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptEnumView.ProtoReflect.Descriptor instead.
func (*ReceiptEnumView) Descriptor() ([]byte, []int) {
	return file_payloads_near_block_transaction_receipt_proto_rawDescGZIP(), []int{1}
}

func (m *ReceiptEnumView) GetVariant() isReceiptEnumView_Variant {
	if m != nil {
		return m.Variant
	}
	return nil
}

func (x *ReceiptEnumView) GetAction() *ReceiptEnumView_Action {
	if x, ok := x.GetVariant().(*ReceiptEnumView_Action_); ok {
		return x.Action
	}
	return nil
}

func (x *ReceiptEnumView) GetData() *ReceiptEnumView_Data {
	if x, ok := x.GetVariant().(*ReceiptEnumView_Data_); ok {
		return x.Data
	}
	return nil
}

type isReceiptEnumView_Variant interface {
	isReceiptEnumView_Variant()
}

type ReceiptEnumView_Action_ struct {
	Action *ReceiptEnumView_Action `protobuf:"bytes,1,opt,name=action,proto3,oneof"`
}

type ReceiptEnumView_Data_ struct {
	Data *ReceiptEnumView_Data `protobuf:"bytes,2,opt,name=data,proto3,oneof"`
}

func (*ReceiptEnumView_Action_) isReceiptEnumView_Variant() {}

func (*ReceiptEnumView_Data_) isReceiptEnumView_Variant() {}

type DataReceiverView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	H256DataId []byte `protobuf:"bytes,1,opt,name=h256_data_id,json=h256DataId,proto3" json:"h256_data_id,omitempty"`
	ReceiverId string `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
}

func (x *DataReceiverView) Reset() {
	*x = DataReceiverView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DataReceiverView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DataReceiverView) ProtoMessage() {}

func (x *DataReceiverView) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DataReceiverView.ProtoReflect.Descriptor instead.
func (*DataReceiverView) Descriptor() ([]byte, []int) {
	return file_payloads_near_block_transaction_receipt_proto_rawDescGZIP(), []int{2}
}

func (x *DataReceiverView) GetH256DataId() []byte {
	if x != nil {
		return x.H256DataId
	}
	return nil
}

func (x *DataReceiverView) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

type ActionView struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Types that are assignable to Variant:
	//
	//	*ActionView_CreateAccount_
	//	*ActionView_DeployContract_
	//	*ActionView_FunctionCall_
	//	*ActionView_Transfer_
	//	*ActionView_Stake_
	//	*ActionView_AddKey_
	//	*ActionView_DeleteKey_
	//	*ActionView_DeleteAccount_
	//	*ActionView_Delegate_
	Variant isActionView_Variant `protobuf_oneof:"variant"`
}

func (x *ActionView) Reset() {
	*x = ActionView{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionView) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionView) ProtoMessage() {}

func (x *ActionView) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionView.ProtoReflect.Descriptor instead.
func (*ActionView) Descriptor() ([]byte, []int) {
	return file_payloads_near_block_transaction_receipt_proto_rawDescGZIP(), []int{3}
}

func (m *ActionView) GetVariant() isActionView_Variant {
	if m != nil {
		return m.Variant
	}
	return nil
}

func (x *ActionView) GetCreateAccount() *ActionView_CreateAccount {
	if x, ok := x.GetVariant().(*ActionView_CreateAccount_); ok {
		return x.CreateAccount
	}
	return nil
}

func (x *ActionView) GetDeployContract() *ActionView_DeployContract {
	if x, ok := x.GetVariant().(*ActionView_DeployContract_); ok {
		return x.DeployContract
	}
	return nil
}

func (x *ActionView) GetFunctionCall() *ActionView_FunctionCall {
	if x, ok := x.GetVariant().(*ActionView_FunctionCall_); ok {
		return x.FunctionCall
	}
	return nil
}

func (x *ActionView) GetTransfer() *ActionView_Transfer {
	if x, ok := x.GetVariant().(*ActionView_Transfer_); ok {
		return x.Transfer
	}
	return nil
}

func (x *ActionView) GetStake() *ActionView_Stake {
	if x, ok := x.GetVariant().(*ActionView_Stake_); ok {
		return x.Stake
	}
	return nil
}

func (x *ActionView) GetAddKey() *ActionView_AddKey {
	if x, ok := x.GetVariant().(*ActionView_AddKey_); ok {
		return x.AddKey
	}
	return nil
}

func (x *ActionView) GetDeleteKey() *ActionView_DeleteKey {
	if x, ok := x.GetVariant().(*ActionView_DeleteKey_); ok {
		return x.DeleteKey
	}
	return nil
}

func (x *ActionView) GetDeleteAccount() *ActionView_DeleteAccount {
	if x, ok := x.GetVariant().(*ActionView_DeleteAccount_); ok {
		return x.DeleteAccount
	}
	return nil
}

func (x *ActionView) GetDelegate() *ActionView_Delegate {
	if x, ok := x.GetVariant().(*ActionView_Delegate_); ok {
		return x.Delegate
	}
	return nil
}

type isActionView_Variant interface {
	isActionView_Variant()
}

type ActionView_CreateAccount_ struct {
	CreateAccount *ActionView_CreateAccount `protobuf:"bytes,1,opt,name=create_account,json=createAccount,proto3,oneof"`
}

type ActionView_DeployContract_ struct {
	DeployContract *ActionView_DeployContract `protobuf:"bytes,2,opt,name=deploy_contract,json=deployContract,proto3,oneof"`
}

type ActionView_FunctionCall_ struct {
	FunctionCall *ActionView_FunctionCall `protobuf:"bytes,3,opt,name=function_call,json=functionCall,proto3,oneof"`
}

type ActionView_Transfer_ struct {
	Transfer *ActionView_Transfer `protobuf:"bytes,4,opt,name=transfer,proto3,oneof"`
}

type ActionView_Stake_ struct {
	Stake *ActionView_Stake `protobuf:"bytes,5,opt,name=stake,proto3,oneof"`
}

type ActionView_AddKey_ struct {
	AddKey *ActionView_AddKey `protobuf:"bytes,6,opt,name=add_key,json=addKey,proto3,oneof"`
}

type ActionView_DeleteKey_ struct {
	DeleteKey *ActionView_DeleteKey `protobuf:"bytes,7,opt,name=delete_key,json=deleteKey,proto3,oneof"`
}

type ActionView_DeleteAccount_ struct {
	DeleteAccount *ActionView_DeleteAccount `protobuf:"bytes,8,opt,name=delete_account,json=deleteAccount,proto3,oneof"`
}

type ActionView_Delegate_ struct {
	Delegate *ActionView_Delegate `protobuf:"bytes,9,opt,name=delegate,proto3,oneof"`
}

func (*ActionView_CreateAccount_) isActionView_Variant() {}

func (*ActionView_DeployContract_) isActionView_Variant() {}

func (*ActionView_FunctionCall_) isActionView_Variant() {}

func (*ActionView_Transfer_) isActionView_Variant() {}

func (*ActionView_Stake_) isActionView_Variant() {}

func (*ActionView_AddKey_) isActionView_Variant() {}

func (*ActionView_DeleteKey_) isActionView_Variant() {}

func (*ActionView_DeleteAccount_) isActionView_Variant() {}

func (*ActionView_Delegate_) isActionView_Variant() {}

type ReceiptEnumView_Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	SignerId            string              `protobuf:"bytes,1,opt,name=signer_id,json=signerId,proto3" json:"signer_id,omitempty"`
	SignerPublicKey     *common.PublicKey   `protobuf:"bytes,2,opt,name=signer_public_key,json=signerPublicKey,proto3" json:"signer_public_key,omitempty"`
	U128GasPrice        []byte              `protobuf:"bytes,3,opt,name=u128_gas_price,json=u128GasPrice,proto3" json:"u128_gas_price,omitempty"`
	OutputDataReceivers []*DataReceiverView `protobuf:"bytes,4,rep,name=output_data_receivers,json=outputDataReceivers,proto3" json:"output_data_receivers,omitempty"`
	H256InputDataIds    [][]byte            `protobuf:"bytes,5,rep,name=h256_input_data_ids,json=h256InputDataIds,proto3" json:"h256_input_data_ids,omitempty"`
	Actions             []*ActionView       `protobuf:"bytes,6,rep,name=actions,proto3" json:"actions,omitempty"`
}

func (x *ReceiptEnumView_Action) Reset() {
	*x = ReceiptEnumView_Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiptEnumView_Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptEnumView_Action) ProtoMessage() {}

func (x *ReceiptEnumView_Action) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptEnumView_Action.ProtoReflect.Descriptor instead.
func (*ReceiptEnumView_Action) Descriptor() ([]byte, []int) {
	return file_payloads_near_block_transaction_receipt_proto_rawDescGZIP(), []int{1, 0}
}

func (x *ReceiptEnumView_Action) GetSignerId() string {
	if x != nil {
		return x.SignerId
	}
	return ""
}

func (x *ReceiptEnumView_Action) GetSignerPublicKey() *common.PublicKey {
	if x != nil {
		return x.SignerPublicKey
	}
	return nil
}

func (x *ReceiptEnumView_Action) GetU128GasPrice() []byte {
	if x != nil {
		return x.U128GasPrice
	}
	return nil
}

func (x *ReceiptEnumView_Action) GetOutputDataReceivers() []*DataReceiverView {
	if x != nil {
		return x.OutputDataReceivers
	}
	return nil
}

func (x *ReceiptEnumView_Action) GetH256InputDataIds() [][]byte {
	if x != nil {
		return x.H256InputDataIds
	}
	return nil
}

func (x *ReceiptEnumView_Action) GetActions() []*ActionView {
	if x != nil {
		return x.Actions
	}
	return nil
}

type ReceiptEnumView_Data struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	H256DataId []byte `protobuf:"bytes,1,opt,name=h256_data_id,json=h256DataId,proto3" json:"h256_data_id,omitempty"`
	Data       []byte `protobuf:"bytes,2,opt,name=data,proto3,oneof" json:"data,omitempty"`
}

func (x *ReceiptEnumView_Data) Reset() {
	*x = ReceiptEnumView_Data{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ReceiptEnumView_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReceiptEnumView_Data) ProtoMessage() {}

func (x *ReceiptEnumView_Data) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReceiptEnumView_Data.ProtoReflect.Descriptor instead.
func (*ReceiptEnumView_Data) Descriptor() ([]byte, []int) {
	return file_payloads_near_block_transaction_receipt_proto_rawDescGZIP(), []int{1, 1}
}

func (x *ReceiptEnumView_Data) GetH256DataId() []byte {
	if x != nil {
		return x.H256DataId
	}
	return nil
}

func (x *ReceiptEnumView_Data) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type ActionView_CreateAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ActionView_CreateAccount) Reset() {
	*x = ActionView_CreateAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionView_CreateAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionView_CreateAccount) ProtoMessage() {}

func (x *ActionView_CreateAccount) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionView_CreateAccount.ProtoReflect.Descriptor instead.
func (*ActionView_CreateAccount) Descriptor() ([]byte, []int) {
	return file_payloads_near_block_transaction_receipt_proto_rawDescGZIP(), []int{3, 0}
}

type ActionView_DeployContract struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code []byte `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
}

func (x *ActionView_DeployContract) Reset() {
	*x = ActionView_DeployContract{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionView_DeployContract) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionView_DeployContract) ProtoMessage() {}

func (x *ActionView_DeployContract) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionView_DeployContract.ProtoReflect.Descriptor instead.
func (*ActionView_DeployContract) Descriptor() ([]byte, []int) {
	return file_payloads_near_block_transaction_receipt_proto_rawDescGZIP(), []int{3, 1}
}

func (x *ActionView_DeployContract) GetCode() []byte {
	if x != nil {
		return x.Code
	}
	return nil
}

type ActionView_FunctionCall struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MethodName  string `protobuf:"bytes,1,opt,name=method_name,json=methodName,proto3" json:"method_name,omitempty"`
	Args        []byte `protobuf:"bytes,2,opt,name=args,proto3" json:"args,omitempty"`
	Gas         uint64 `protobuf:"varint,3,opt,name=gas,proto3" json:"gas,omitempty"`
	U128Deposit []byte `protobuf:"bytes,4,opt,name=u128_deposit,json=u128Deposit,proto3" json:"u128_deposit,omitempty"`
}

func (x *ActionView_FunctionCall) Reset() {
	*x = ActionView_FunctionCall{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionView_FunctionCall) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionView_FunctionCall) ProtoMessage() {}

func (x *ActionView_FunctionCall) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionView_FunctionCall.ProtoReflect.Descriptor instead.
func (*ActionView_FunctionCall) Descriptor() ([]byte, []int) {
	return file_payloads_near_block_transaction_receipt_proto_rawDescGZIP(), []int{3, 2}
}

func (x *ActionView_FunctionCall) GetMethodName() string {
	if x != nil {
		return x.MethodName
	}
	return ""
}

func (x *ActionView_FunctionCall) GetArgs() []byte {
	if x != nil {
		return x.Args
	}
	return nil
}

func (x *ActionView_FunctionCall) GetGas() uint64 {
	if x != nil {
		return x.Gas
	}
	return 0
}

func (x *ActionView_FunctionCall) GetU128Deposit() []byte {
	if x != nil {
		return x.U128Deposit
	}
	return nil
}

type ActionView_Transfer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	U128Deposit []byte `protobuf:"bytes,1,opt,name=u128_deposit,json=u128Deposit,proto3" json:"u128_deposit,omitempty"`
}

func (x *ActionView_Transfer) Reset() {
	*x = ActionView_Transfer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionView_Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionView_Transfer) ProtoMessage() {}

func (x *ActionView_Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionView_Transfer.ProtoReflect.Descriptor instead.
func (*ActionView_Transfer) Descriptor() ([]byte, []int) {
	return file_payloads_near_block_transaction_receipt_proto_rawDescGZIP(), []int{3, 3}
}

func (x *ActionView_Transfer) GetU128Deposit() []byte {
	if x != nil {
		return x.U128Deposit
	}
	return nil
}

type ActionView_Stake struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	U128Stake []byte            `protobuf:"bytes,1,opt,name=u128_stake,json=u128Stake,proto3" json:"u128_stake,omitempty"`
	PublicKey *common.PublicKey `protobuf:"bytes,2,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *ActionView_Stake) Reset() {
	*x = ActionView_Stake{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionView_Stake) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionView_Stake) ProtoMessage() {}

func (x *ActionView_Stake) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionView_Stake.ProtoReflect.Descriptor instead.
func (*ActionView_Stake) Descriptor() ([]byte, []int) {
	return file_payloads_near_block_transaction_receipt_proto_rawDescGZIP(), []int{3, 4}
}

func (x *ActionView_Stake) GetU128Stake() []byte {
	if x != nil {
		return x.U128Stake
	}
	return nil
}

func (x *ActionView_Stake) GetPublicKey() *common.PublicKey {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type ActionView_AddKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey *common.PublicKey `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	AccessKey *AccessKeyView    `protobuf:"bytes,2,opt,name=access_key,json=accessKey,proto3" json:"access_key,omitempty"`
}

func (x *ActionView_AddKey) Reset() {
	*x = ActionView_AddKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionView_AddKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionView_AddKey) ProtoMessage() {}

func (x *ActionView_AddKey) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionView_AddKey.ProtoReflect.Descriptor instead.
func (*ActionView_AddKey) Descriptor() ([]byte, []int) {
	return file_payloads_near_block_transaction_receipt_proto_rawDescGZIP(), []int{3, 5}
}

func (x *ActionView_AddKey) GetPublicKey() *common.PublicKey {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *ActionView_AddKey) GetAccessKey() *AccessKeyView {
	if x != nil {
		return x.AccessKey
	}
	return nil
}

type ActionView_DeleteKey struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicKey *common.PublicKey `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *ActionView_DeleteKey) Reset() {
	*x = ActionView_DeleteKey{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionView_DeleteKey) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionView_DeleteKey) ProtoMessage() {}

func (x *ActionView_DeleteKey) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionView_DeleteKey.ProtoReflect.Descriptor instead.
func (*ActionView_DeleteKey) Descriptor() ([]byte, []int) {
	return file_payloads_near_block_transaction_receipt_proto_rawDescGZIP(), []int{3, 6}
}

func (x *ActionView_DeleteKey) GetPublicKey() *common.PublicKey {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type ActionView_DeleteAccount struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	BeneficiaryId string `protobuf:"bytes,1,opt,name=beneficiary_id,json=beneficiaryId,proto3" json:"beneficiary_id,omitempty"`
}

func (x *ActionView_DeleteAccount) Reset() {
	*x = ActionView_DeleteAccount{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionView_DeleteAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionView_DeleteAccount) ProtoMessage() {}

func (x *ActionView_DeleteAccount) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionView_DeleteAccount.ProtoReflect.Descriptor instead.
func (*ActionView_DeleteAccount) Descriptor() ([]byte, []int) {
	return file_payloads_near_block_transaction_receipt_proto_rawDescGZIP(), []int{3, 7}
}

func (x *ActionView_DeleteAccount) GetBeneficiaryId() string {
	if x != nil {
		return x.BeneficiaryId
	}
	return ""
}

type ActionView_Delegate struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DelegateAction *ActionView_Delegate_DelegateAction `protobuf:"bytes,1,opt,name=delegate_action,json=delegateAction,proto3" json:"delegate_action,omitempty"`
	Signature      *common.Signature                   `protobuf:"bytes,2,opt,name=signature,proto3" json:"signature,omitempty"`
}

func (x *ActionView_Delegate) Reset() {
	*x = ActionView_Delegate{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionView_Delegate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionView_Delegate) ProtoMessage() {}

func (x *ActionView_Delegate) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionView_Delegate.ProtoReflect.Descriptor instead.
func (*ActionView_Delegate) Descriptor() ([]byte, []int) {
	return file_payloads_near_block_transaction_receipt_proto_rawDescGZIP(), []int{3, 8}
}

func (x *ActionView_Delegate) GetDelegateAction() *ActionView_Delegate_DelegateAction {
	if x != nil {
		return x.DelegateAction
	}
	return nil
}

func (x *ActionView_Delegate) GetSignature() *common.Signature {
	if x != nil {
		return x.Signature
	}
	return nil
}

// This action allows to execute the inner actions behalf of the defined sender.
type ActionView_Delegate_DelegateAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Signer of the delegated actions
	SenderId string `protobuf:"bytes,1,opt,name=sender_id,json=senderId,proto3" json:"sender_id,omitempty"`
	// Receiver of the delegated actions.
	ReceiverId string `protobuf:"bytes,2,opt,name=receiver_id,json=receiverId,proto3" json:"receiver_id,omitempty"`
	// List of actions to be executed.
	//
	// With the meta transactions MVP defined in NEP-366, nested
	// DelegateActions are not allowed. A separate type is used to enforce it.
	Actions []*ActionView_Delegate_DelegateAction_NonDelegateAction `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	// / Nonce to ensure that the same delegate action is not sent twice by a
	// / relayer and should match for given account's `public_key`.
	// / After this action is processed it will increment.
	Nonce uint64 `protobuf:"varint,4,opt,name=nonce,proto3" json:"nonce,omitempty"`
	// / The maximal height of the block in the blockchain below which the given DelegateAction is valid.
	MaxBlockHeight uint64 `protobuf:"varint,5,opt,name=max_block_height,json=maxBlockHeight,proto3" json:"max_block_height,omitempty"`
	// / Public key used to sign this delegated action.
	PublicKey *common.PublicKey `protobuf:"bytes,6,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
}

func (x *ActionView_Delegate_DelegateAction) Reset() {
	*x = ActionView_Delegate_DelegateAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionView_Delegate_DelegateAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionView_Delegate_DelegateAction) ProtoMessage() {}

func (x *ActionView_Delegate_DelegateAction) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionView_Delegate_DelegateAction.ProtoReflect.Descriptor instead.
func (*ActionView_Delegate_DelegateAction) Descriptor() ([]byte, []int) {
	return file_payloads_near_block_transaction_receipt_proto_rawDescGZIP(), []int{3, 8, 0}
}

func (x *ActionView_Delegate_DelegateAction) GetSenderId() string {
	if x != nil {
		return x.SenderId
	}
	return ""
}

func (x *ActionView_Delegate_DelegateAction) GetReceiverId() string {
	if x != nil {
		return x.ReceiverId
	}
	return ""
}

func (x *ActionView_Delegate_DelegateAction) GetActions() []*ActionView_Delegate_DelegateAction_NonDelegateAction {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *ActionView_Delegate_DelegateAction) GetNonce() uint64 {
	if x != nil {
		return x.Nonce
	}
	return 0
}

func (x *ActionView_Delegate_DelegateAction) GetMaxBlockHeight() uint64 {
	if x != nil {
		return x.MaxBlockHeight
	}
	return 0
}

func (x *ActionView_Delegate_DelegateAction) GetPublicKey() *common.PublicKey {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

type ActionView_Delegate_DelegateAction_NonDelegateAction struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Action *ActionView `protobuf:"bytes,1,opt,name=action,proto3" json:"action,omitempty"`
}

func (x *ActionView_Delegate_DelegateAction_NonDelegateAction) Reset() {
	*x = ActionView_Delegate_DelegateAction_NonDelegateAction{}
	if protoimpl.UnsafeEnabled {
		mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ActionView_Delegate_DelegateAction_NonDelegateAction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActionView_Delegate_DelegateAction_NonDelegateAction) ProtoMessage() {}

func (x *ActionView_Delegate_DelegateAction_NonDelegateAction) ProtoReflect() protoreflect.Message {
	mi := &file_payloads_near_block_transaction_receipt_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActionView_Delegate_DelegateAction_NonDelegateAction.ProtoReflect.Descriptor instead.
func (*ActionView_Delegate_DelegateAction_NonDelegateAction) Descriptor() ([]byte, []int) {
	return file_payloads_near_block_transaction_receipt_proto_rawDescGZIP(), []int{3, 8, 0, 0}
}

func (x *ActionView_Delegate_DelegateAction_NonDelegateAction) GetAction() *ActionView {
	if x != nil {
		return x.Action
	}
	return nil
}

var File_payloads_near_block_transaction_receipt_proto protoreflect.FileDescriptor

var file_payloads_near_block_transaction_receipt_proto_rawDesc = []byte{
	0x0a, 0x2d, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x2f, 0x6e, 0x65, 0x61, 0x72, 0x5f,
	0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x2f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a,
	0x13, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x30, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x2f, 0x6e,
	0x65, 0x61, 0x72, 0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x5f, 0x6b, 0x65, 0x79,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xa9, 0x01, 0x0a, 0x0b, 0x52, 0x65, 0x63, 0x65, 0x69,
	0x70, 0x74, 0x56, 0x69, 0x65, 0x77, 0x12, 0x25, 0x0a, 0x0e, 0x70, 0x72, 0x65, 0x64, 0x65, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d,
	0x70, 0x72, 0x65, 0x64, 0x65, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a,
	0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x26,
	0x0a, 0x0f, 0x68, 0x32, 0x35, 0x36, 0x5f, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x5f, 0x69,
	0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0d, 0x68, 0x32, 0x35, 0x36, 0x52, 0x65, 0x63,
	0x65, 0x69, 0x70, 0x74, 0x49, 0x64, 0x12, 0x2a, 0x0a, 0x07, 0x72, 0x65, 0x63, 0x65, 0x69, 0x70,
	0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x10, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70,
	0x74, 0x45, 0x6e, 0x75, 0x6d, 0x56, 0x69, 0x65, 0x77, 0x52, 0x07, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x70, 0x74, 0x22, 0xeb, 0x03, 0x0a, 0x0f, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74, 0x45, 0x6e,
	0x75, 0x6d, 0x56, 0x69, 0x65, 0x77, 0x12, 0x31, 0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70, 0x74,
	0x45, 0x6e, 0x75, 0x6d, 0x56, 0x69, 0x65, 0x77, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x48,
	0x00, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x2b, 0x0a, 0x04, 0x64, 0x61, 0x74,
	0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x52, 0x65, 0x63, 0x65, 0x69, 0x70,
	0x74, 0x45, 0x6e, 0x75, 0x6d, 0x56, 0x69, 0x65, 0x77, 0x2e, 0x44, 0x61, 0x74, 0x61, 0x48, 0x00,
	0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x1a, 0xa0, 0x02, 0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x1b, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x49, 0x64, 0x12, 0x36,
	0x0a, 0x11, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x5f, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f,
	0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x0f, 0x73, 0x69, 0x67, 0x6e, 0x65, 0x72, 0x50, 0x75, 0x62,
	0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x0e, 0x75, 0x31, 0x32, 0x38, 0x5f, 0x67,
	0x61, 0x73, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0c,
	0x75, 0x31, 0x32, 0x38, 0x47, 0x61, 0x73, 0x50, 0x72, 0x69, 0x63, 0x65, 0x12, 0x45, 0x0a, 0x15,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x72, 0x65, 0x63, 0x65,
	0x69, 0x76, 0x65, 0x72, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x44, 0x61,
	0x74, 0x61, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x56, 0x69, 0x65, 0x77, 0x52, 0x13,
	0x6f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x73, 0x12, 0x2d, 0x0a, 0x13, 0x68, 0x32, 0x35, 0x36, 0x5f, 0x69, 0x6e, 0x70, 0x75,
	0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x69, 0x64, 0x73, 0x18, 0x05, 0x20, 0x03, 0x28, 0x0c,
	0x52, 0x10, 0x68, 0x32, 0x35, 0x36, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x44, 0x61, 0x74, 0x61, 0x49,
	0x64, 0x73, 0x12, 0x25, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x06, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x0b, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x69, 0x65, 0x77,
	0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x1a, 0x4a, 0x0a, 0x04, 0x44, 0x61, 0x74,
	0x61, 0x12, 0x20, 0x0a, 0x0c, 0x68, 0x32, 0x35, 0x36, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x5f, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x68, 0x32, 0x35, 0x36, 0x44, 0x61, 0x74,
	0x61, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x0c, 0x48, 0x00, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x88, 0x01, 0x01, 0x42, 0x07, 0x0a, 0x05,
	0x5f, 0x64, 0x61, 0x74, 0x61, 0x42, 0x09, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74,
	0x22, 0x55, 0x0a, 0x10, 0x44, 0x61, 0x74, 0x61, 0x52, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72,
	0x56, 0x69, 0x65, 0x77, 0x12, 0x20, 0x0a, 0x0c, 0x68, 0x32, 0x35, 0x36, 0x5f, 0x64, 0x61, 0x74,
	0x61, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0a, 0x68, 0x32, 0x35, 0x36,
	0x44, 0x61, 0x74, 0x61, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76,
	0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x72, 0x65, 0x63,
	0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x22, 0xf4, 0x0b, 0x0a, 0x0a, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x56, 0x69, 0x65, 0x77, 0x12, 0x42, 0x0a, 0x0e, 0x63, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19,
	0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x69, 0x65, 0x77, 0x2e, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x63, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x45, 0x0a, 0x0f, 0x64, 0x65,
	0x70, 0x6c, 0x6f, 0x79, 0x5f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x69, 0x65, 0x77,
	0x2e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63, 0x74, 0x48,
	0x00, 0x52, 0x0e, 0x64, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x72, 0x61, 0x63,
	0x74, 0x12, 0x3f, 0x0a, 0x0d, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x63, 0x61,
	0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x18, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f,
	0x6e, 0x56, 0x69, 0x65, 0x77, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61,
	0x6c, 0x6c, 0x48, 0x00, 0x52, 0x0c, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x43, 0x61,
	0x6c, 0x6c, 0x12, 0x32, 0x0a, 0x08, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x14, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x69, 0x65,
	0x77, 0x2e, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x48, 0x00, 0x52, 0x08, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x29, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x11, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x69,
	0x65, 0x77, 0x2e, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x48, 0x00, 0x52, 0x05, 0x73, 0x74, 0x61, 0x6b,
	0x65, 0x12, 0x2d, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x12, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x69, 0x65, 0x77, 0x2e,
	0x41, 0x64, 0x64, 0x4b, 0x65, 0x79, 0x48, 0x00, 0x52, 0x06, 0x61, 0x64, 0x64, 0x4b, 0x65, 0x79,
	0x12, 0x36, 0x0a, 0x0a, 0x64, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x69, 0x65,
	0x77, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x48, 0x00, 0x52, 0x09, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x4b, 0x65, 0x79, 0x12, 0x42, 0x0a, 0x0e, 0x64, 0x65, 0x6c, 0x65,
	0x74, 0x65, 0x5f, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x08, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x19, 0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x69, 0x65, 0x77, 0x2e, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x64,
	0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x32, 0x0a, 0x08,
	0x64, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x69, 0x65, 0x77, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x48, 0x00, 0x52, 0x08, 0x64, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65,
	0x1a, 0x0f, 0x0a, 0x0d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x1a, 0x24, 0x0a, 0x0e, 0x44, 0x65, 0x70, 0x6c, 0x6f, 0x79, 0x43, 0x6f, 0x6e, 0x74, 0x72,
	0x61, 0x63, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0c, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x1a, 0x78, 0x0a, 0x0c, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x43, 0x61, 0x6c, 0x6c, 0x12, 0x1f, 0x0a, 0x0b, 0x6d, 0x65, 0x74, 0x68, 0x6f,
	0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x6d, 0x65,
	0x74, 0x68, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x61, 0x72, 0x67, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x04, 0x61, 0x72, 0x67, 0x73, 0x12, 0x10, 0x0a, 0x03,
	0x67, 0x61, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x03, 0x67, 0x61, 0x73, 0x12, 0x21,
	0x0a, 0x0c, 0x75, 0x31, 0x32, 0x38, 0x5f, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x75, 0x31, 0x32, 0x38, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69,
	0x74, 0x1a, 0x2d, 0x0a, 0x08, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x12, 0x21, 0x0a,
	0x0c, 0x75, 0x31, 0x32, 0x38, 0x5f, 0x64, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0c, 0x52, 0x0b, 0x75, 0x31, 0x32, 0x38, 0x44, 0x65, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x1a, 0x51, 0x0a, 0x05, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x31, 0x32,
	0x38, 0x5f, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x09, 0x75,
	0x31, 0x32, 0x38, 0x53, 0x74, 0x61, 0x6b, 0x65, 0x12, 0x29, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c,
	0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63,
	0x4b, 0x65, 0x79, 0x1a, 0x62, 0x0a, 0x06, 0x41, 0x64, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x29, 0x0a,
	0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x09, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x2d, 0x0a, 0x0a, 0x61, 0x63, 0x63, 0x65,
	0x73, 0x73, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0e, 0x2e, 0x41,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x56, 0x69, 0x65, 0x77, 0x52, 0x09, 0x61, 0x63,
	0x63, 0x65, 0x73, 0x73, 0x4b, 0x65, 0x79, 0x1a, 0x36, 0x0a, 0x09, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x4b, 0x65, 0x79, 0x12, 0x29, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69,
	0x63, 0x4b, 0x65, 0x79, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x1a,
	0x36, 0x0a, 0x0d, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x12, 0x25, 0x0a, 0x0e, 0x62, 0x65, 0x6e, 0x65, 0x66, 0x69, 0x63, 0x69, 0x61, 0x72, 0x79, 0x5f,
	0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x62, 0x65, 0x6e, 0x65, 0x66, 0x69,
	0x63, 0x69, 0x61, 0x72, 0x79, 0x49, 0x64, 0x1a, 0xc9, 0x03, 0x0a, 0x08, 0x44, 0x65, 0x6c, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x12, 0x4c, 0x0a, 0x0f, 0x64, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65,
	0x5f, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x23, 0x2e,
	0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x69, 0x65, 0x77, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x67,
	0x61, 0x74, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x52, 0x0e, 0x64, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x12, 0x28, 0x0a, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x53, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72,
	0x65, 0x52, 0x09, 0x73, 0x69, 0x67, 0x6e, 0x61, 0x74, 0x75, 0x72, 0x65, 0x1a, 0xc4, 0x02, 0x0a,
	0x0e, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12,
	0x1b, 0x0a, 0x09, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x73, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1f, 0x0a, 0x0b,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x72, 0x49, 0x64, 0x12, 0x4f, 0x0a,
	0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x35,
	0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x69, 0x65, 0x77, 0x2e, 0x44, 0x65, 0x6c, 0x65,
	0x67, 0x61, 0x74, 0x65, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x4e, 0x6f, 0x6e, 0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x14,
	0x0a, 0x05, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x05, 0x6e,
	0x6f, 0x6e, 0x63, 0x65, 0x12, 0x28, 0x0a, 0x10, 0x6d, 0x61, 0x78, 0x5f, 0x62, 0x6c, 0x6f, 0x63,
	0x6b, 0x5f, 0x68, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e,
	0x6d, 0x61, 0x78, 0x42, 0x6c, 0x6f, 0x63, 0x6b, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x29,
	0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x0a, 0x2e, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x52, 0x09,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x1a, 0x38, 0x0a, 0x11, 0x4e, 0x6f, 0x6e,
	0x44, 0x65, 0x6c, 0x65, 0x67, 0x61, 0x74, 0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x23,
	0x0a, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x0b,
	0x2e, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x69, 0x65, 0x77, 0x52, 0x06, 0x61, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x42, 0x09, 0x0a, 0x07, 0x76, 0x61, 0x72, 0x69, 0x61, 0x6e, 0x74, 0x42, 0x5e,
	0x5a, 0x5c, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x75, 0x72,
	0x6f, 0x72, 0x61, 0x2d, 0x69, 0x73, 0x2d, 0x6e, 0x65, 0x61, 0x72, 0x2f, 0x62, 0x6f, 0x72, 0x65,
	0x61, 0x6c, 0x69, 0x73, 0x2d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f,
	0x67, 0x6f, 0x2f, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x73, 0x2f, 0x6e, 0x65, 0x61, 0x72,
	0x5f, 0x62, 0x6c, 0x6f, 0x63, 0x6b, 0x2f, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x3b, 0x74, 0x72, 0x61, 0x6e, 0x73, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_payloads_near_block_transaction_receipt_proto_rawDescOnce sync.Once
	file_payloads_near_block_transaction_receipt_proto_rawDescData = file_payloads_near_block_transaction_receipt_proto_rawDesc
)

func file_payloads_near_block_transaction_receipt_proto_rawDescGZIP() []byte {
	file_payloads_near_block_transaction_receipt_proto_rawDescOnce.Do(func() {
		file_payloads_near_block_transaction_receipt_proto_rawDescData = protoimpl.X.CompressGZIP(file_payloads_near_block_transaction_receipt_proto_rawDescData)
	})
	return file_payloads_near_block_transaction_receipt_proto_rawDescData
}

var file_payloads_near_block_transaction_receipt_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_payloads_near_block_transaction_receipt_proto_goTypes = []interface{}{
	(*ReceiptView)(nil),                                          // 0: ReceiptView
	(*ReceiptEnumView)(nil),                                      // 1: ReceiptEnumView
	(*DataReceiverView)(nil),                                     // 2: DataReceiverView
	(*ActionView)(nil),                                           // 3: ActionView
	(*ReceiptEnumView_Action)(nil),                               // 4: ReceiptEnumView.Action
	(*ReceiptEnumView_Data)(nil),                                 // 5: ReceiptEnumView.Data
	(*ActionView_CreateAccount)(nil),                             // 6: ActionView.CreateAccount
	(*ActionView_DeployContract)(nil),                            // 7: ActionView.DeployContract
	(*ActionView_FunctionCall)(nil),                              // 8: ActionView.FunctionCall
	(*ActionView_Transfer)(nil),                                  // 9: ActionView.Transfer
	(*ActionView_Stake)(nil),                                     // 10: ActionView.Stake
	(*ActionView_AddKey)(nil),                                    // 11: ActionView.AddKey
	(*ActionView_DeleteKey)(nil),                                 // 12: ActionView.DeleteKey
	(*ActionView_DeleteAccount)(nil),                             // 13: ActionView.DeleteAccount
	(*ActionView_Delegate)(nil),                                  // 14: ActionView.Delegate
	(*ActionView_Delegate_DelegateAction)(nil),                   // 15: ActionView.Delegate.DelegateAction
	(*ActionView_Delegate_DelegateAction_NonDelegateAction)(nil), // 16: ActionView.Delegate.DelegateAction.NonDelegateAction
	(*common.PublicKey)(nil),                                     // 17: PublicKey
	(*AccessKeyView)(nil),                                        // 18: AccessKeyView
	(*common.Signature)(nil),                                     // 19: Signature
}
var file_payloads_near_block_transaction_receipt_proto_depIdxs = []int32{
	1,  // 0: ReceiptView.receipt:type_name -> ReceiptEnumView
	4,  // 1: ReceiptEnumView.action:type_name -> ReceiptEnumView.Action
	5,  // 2: ReceiptEnumView.data:type_name -> ReceiptEnumView.Data
	6,  // 3: ActionView.create_account:type_name -> ActionView.CreateAccount
	7,  // 4: ActionView.deploy_contract:type_name -> ActionView.DeployContract
	8,  // 5: ActionView.function_call:type_name -> ActionView.FunctionCall
	9,  // 6: ActionView.transfer:type_name -> ActionView.Transfer
	10, // 7: ActionView.stake:type_name -> ActionView.Stake
	11, // 8: ActionView.add_key:type_name -> ActionView.AddKey
	12, // 9: ActionView.delete_key:type_name -> ActionView.DeleteKey
	13, // 10: ActionView.delete_account:type_name -> ActionView.DeleteAccount
	14, // 11: ActionView.delegate:type_name -> ActionView.Delegate
	17, // 12: ReceiptEnumView.Action.signer_public_key:type_name -> PublicKey
	2,  // 13: ReceiptEnumView.Action.output_data_receivers:type_name -> DataReceiverView
	3,  // 14: ReceiptEnumView.Action.actions:type_name -> ActionView
	17, // 15: ActionView.Stake.public_key:type_name -> PublicKey
	17, // 16: ActionView.AddKey.public_key:type_name -> PublicKey
	18, // 17: ActionView.AddKey.access_key:type_name -> AccessKeyView
	17, // 18: ActionView.DeleteKey.public_key:type_name -> PublicKey
	15, // 19: ActionView.Delegate.delegate_action:type_name -> ActionView.Delegate.DelegateAction
	19, // 20: ActionView.Delegate.signature:type_name -> Signature
	16, // 21: ActionView.Delegate.DelegateAction.actions:type_name -> ActionView.Delegate.DelegateAction.NonDelegateAction
	17, // 22: ActionView.Delegate.DelegateAction.public_key:type_name -> PublicKey
	3,  // 23: ActionView.Delegate.DelegateAction.NonDelegateAction.action:type_name -> ActionView
	24, // [24:24] is the sub-list for method output_type
	24, // [24:24] is the sub-list for method input_type
	24, // [24:24] is the sub-list for extension type_name
	24, // [24:24] is the sub-list for extension extendee
	0,  // [0:24] is the sub-list for field type_name
}

func init() { file_payloads_near_block_transaction_receipt_proto_init() }
func file_payloads_near_block_transaction_receipt_proto_init() {
	if File_payloads_near_block_transaction_receipt_proto != nil {
		return
	}
	file_payloads_near_block_transaction_access_key_proto_init()
	if !protoimpl.UnsafeEnabled {
		file_payloads_near_block_transaction_receipt_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiptView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_near_block_transaction_receipt_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiptEnumView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_near_block_transaction_receipt_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DataReceiverView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_near_block_transaction_receipt_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionView); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_near_block_transaction_receipt_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiptEnumView_Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_near_block_transaction_receipt_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ReceiptEnumView_Data); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_near_block_transaction_receipt_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionView_CreateAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_near_block_transaction_receipt_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionView_DeployContract); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_near_block_transaction_receipt_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionView_FunctionCall); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_near_block_transaction_receipt_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionView_Transfer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_near_block_transaction_receipt_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionView_Stake); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_near_block_transaction_receipt_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionView_AddKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_near_block_transaction_receipt_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionView_DeleteKey); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_near_block_transaction_receipt_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionView_DeleteAccount); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_near_block_transaction_receipt_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionView_Delegate); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_near_block_transaction_receipt_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionView_Delegate_DelegateAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_payloads_near_block_transaction_receipt_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ActionView_Delegate_DelegateAction_NonDelegateAction); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_payloads_near_block_transaction_receipt_proto_msgTypes[1].OneofWrappers = []interface{}{
		(*ReceiptEnumView_Action_)(nil),
		(*ReceiptEnumView_Data_)(nil),
	}
	file_payloads_near_block_transaction_receipt_proto_msgTypes[3].OneofWrappers = []interface{}{
		(*ActionView_CreateAccount_)(nil),
		(*ActionView_DeployContract_)(nil),
		(*ActionView_FunctionCall_)(nil),
		(*ActionView_Transfer_)(nil),
		(*ActionView_Stake_)(nil),
		(*ActionView_AddKey_)(nil),
		(*ActionView_DeleteKey_)(nil),
		(*ActionView_DeleteAccount_)(nil),
		(*ActionView_Delegate_)(nil),
	}
	file_payloads_near_block_transaction_receipt_proto_msgTypes[5].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_payloads_near_block_transaction_receipt_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_payloads_near_block_transaction_receipt_proto_goTypes,
		DependencyIndexes: file_payloads_near_block_transaction_receipt_proto_depIdxs,
		MessageInfos:      file_payloads_near_block_transaction_receipt_proto_msgTypes,
	}.Build()
	File_payloads_near_block_transaction_receipt_proto = out.File
	file_payloads_near_block_transaction_receipt_proto_rawDesc = nil
	file_payloads_near_block_transaction_receipt_proto_goTypes = nil
	file_payloads_near_block_transaction_receipt_proto_depIdxs = nil
}
