---
on:
  push:
    branches:
      - main
  pull_request:


name: Checks
jobs:
  checks:
    name: Checks
    runs-on: [ self-hosted, heavy ]
    steps:
      - name: Clone the repository
        uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: |
            ${{ secrets.SSH_BOREALIS_RS }}
      - name: Install protoc
        run: |
          curl -sLO https://github.com/protocolbuffers/protobuf/releases/download/v24.0/protoc-24.0-linux-x86_64.zip
          apt-get -y install unzip liblz4-dev
          unzip protoc-24.0-linux-x86_64.zip -d $HOME
      - name: Run fmt checks
        run: cargo fmt --check --all
      - name: Run clippy checks
        run: |
          cargo clippy --workspace --all-targets -- -D clippy::all
          cargo clippy --workspace --all-targets --features ext-connector -- -D clippy::all
      - name: Run tests
        run: |
          cargo test --workspace
          cargo test --workspace --features ext-connector

env:
  PROTOC: /root/bin/protoc
